# Generated by Django 5.1.7 on 2025-03-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='MSP',
            field=models.CharField(max_length=50),
        ),
    ]
