# Generated by Django 5.1.7 on 2025-03-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IntercroppingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_crop', models.CharField(max_length=100)),
                ('benefits', models.TextField()),
                ('companion_crops', models.ManyToManyField(related_name='intercropping_data', to='MixedFarming.companioncrop')),
            ],
        ),
    ]
