# Generated by Django 5.1.7 on 2025-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixedFarming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroppingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='intercroppingdata',
            name='patterns',
            field=models.ManyToManyField(related_name='intercropping_data', to='MixedFarming.croppingpattern'),
        ),
    ]
