# Generated by Django 5.1.7 on 2025-03-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixedFarming', '0003_intercroppingdata_companion_crop_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercroppingdata',
            name='main_crop_percentage',
            field=models.FloatField(default=0),
        ),
    ]
