# Generated by Django 5.1.7 on 2025-03-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MixedFarming', '0004_intercroppingdata_main_crop_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intercroppingdata',
            name='main_crop_percentage',
        ),
    ]
